# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:latest AS build

WORKDIR /app

COPY . .

RUN go mod tidy

RUN go build -o /app/golang-app main.go

##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /app

COPY --from=build /app/golang-app /app/golang-app

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/app/golang-app"]