version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    container_name: docker-go-compose
    restart: unless-stopped
    environment:
      - PORT=:8080
    ports:
      - "8080:8080"